### ISSUE TITLE
[ossia-Max] (at)rate buffers values in ossia.remote

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#317] opened 2017-12-07 20:21 UTC
as demonstrated in the patcher below, when \@rate is set at a smaller rate than that which values are fed, ossia.remote will buffer values and output them all at once every \@rate ms
I don't think that's how this is supposed to work (it should output values just once every \@rate ms)

<pre><code>
----------begin_max5_patcher----------
615.3ocsVEraiBCD8L7Uf3LajMwXB6odt+BqVE4P7RbEXiLltopp+6q8XHMI
JgjsgdHf8jwy32yy7LuGFDuQsm2EG8yneEED7dXP.XxYHXXdPbCaeYMqCbKV
x+qZyKwI9+xv2a.ysZgzLZsy7VMGLOZQ12n5M0bCDDzf0VlobmPVsVyKM9Mw
xrUKPIQKI49WtmooKPQ+dXMhsPfs6gejcTzExwfic19HLz8H4w.kpqSvVn4M
JCOxv6LqaYZVC2v0QOoYViXDBMtrRUsR6QAZANMiTjXGjWPQ4qbiVUPvX6H7
Qn4VL0xqyTzhEYVtoHySQESxTG1j9Xadqk6ihMuC+NrtuK1zDs4dKPv2r.AW
.EHoSVfPnWE1aXxpYDxFUUkEQON7xgiSLNCNbIiX7hnibUz45EOrjC0rq4R1
F+FC8MeVqYxspFa6Ad93jBj6Ud1jm336iSNA2oyGts7rV4TElOXSf5c5zvF8
UJzSmakxOUGOUr7hJjjBDtfl.iVgVBhkY3bJI++ShL8VLXJgBD4J7TTHlNsD
4s0J.OhqExyuPE1YN6mxqcpdc4XNFUoi9bys0xgBIyHTxicx6yEO5t2D45Rt
YhbDximIxcjIBZNxz8PdmAbkdKWecku4M0zKmZzikZ5WpjwWpxZaekq6FbFx
gsY+EeKZdBLUH8SgODIVyeUL5OArvz1lNisiqW6aR2S8WKE2nrHT1KF3WK5B
GZlOq8PZEIfk9LqQ0vVuSTYgd0NCe6Zk8hjpg6Usn6Or9ZyoTBqrjKMGor.c
4H20mv8EfThG5ICTq1tfyUUharQVLdf3XnvOB+m0Fvn+
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment] 2017-12-08 12:08
this is the expected behavior, at least this is how it was specified

**Comment by avilleret** [comment] 2017-12-08 12:11
just for the record, `@rate` attribute defined the period of polling interval
in between everything that comes is kept into a queue
and the queue is flushed when polling
keeping everything in the queue garantee that you'll not miss anything (as opposed to a drop behavior, that some other OSC implementation might have).
if this is a problem, there might be a design issue with your patch :-)

**Comment by bltzr** [comment] 2017-12-09 13:49
who specified things this way ? (wasn't me...)
IMHO that's a quite strange way to do it, but why not, this is not very critical...

**Comment by jln-** [comment] 2017-12-09 13:57
Seems a bit strange to me as well. 

As a side note, "rate" is also a bit misleading, I think (with such a name I'd expect a frequency value rather than an interval).

**Comment by bltzr** [comment] 2017-12-09 13:59
> with such a name I'd expect a frequency value rather than an interval

absolutely makes sense - how would you change that ?
by specifying (at)rate in Hz ?
or changing its name? (at)interval (at)poll ? (not convinced about any of both)

**Comment by jln-** [comment] 2017-12-09 14:34
I think I'd favor (at)rate in Hz but just my opinion - not sure there is an absolute use case for this.

Otherwise, after a quick look at Max objects, it seems (at)interval is used here and there. (at)refresh could be a candidate as well.

If we are to change (at)rate in hz, maybe that would be better to do this before the release, since it'd break quite some things in old patches

**Comment by bltzr** [comment] 2017-12-09 14:57
for me using ms sounds more « natural » than hz for this kind of things

why not (at)refresh… but really that doesn’t bother me so much that it’s called rate and uses ms

also, all other libossia implementations use ```rate``` for this, so maybe we should favor general consistency ??
https://ossia.github.io/?plaintext--max#refresh-rate
at least, if we keep it this way, we should specify it’s in ms in the doc

that’s not very critical, anyway, I’d say, we have **a lot** of more pressing (even if that’s not so hard to change… we just need to avoid forgetting instances of (at)rate when batch-replacing)

**Comment by avilleret** [comment] 2017-12-09 16:07
i'm pretty sure the name was discussed on Gitter between @jln- and @bltzr during a full-of-meme afternoon, but if you want to discuss a bit more, please let me know your choice (but don't revert it 2 week after :-) ).
Concerning the queuing behavior, this is needed for Pd and Max : to avoid crash, new value can be outputed only on scheduler tick.
And at the beginning there was only one queue for all matching nodes, so we need to keep every value in the value or we may miss some parameter change. Here comes the spec.
Now, there is one queue per matching node, so we can rethink the way values are kept or not.
But I'm not sure it is needed.

**Comment by bltzr** [comment] 2017-12-09 16:22
about the name: I don't really care, but if you want to change it, @jln- please go ahead

I agree on the queuing behavior, to make it safe

but I don't see one situation where we want the n last values of one parameter to be output at once - I'd only keep the last one, but I might be overseeing things...

**Comment by avilleret** [comment] 2017-12-09 20:56
if you want to detect drop or return-to-zero behavior, then you need all values.
one simple example : a sustain pedal that trigs a sample, 
it the pedal is pressed and released between 2 poll, then you'll miss the press state, which is bad I think

So I do think its safe to keep it like that.
In most case, your patch would run faster than your input source, so most of the time there will be only one value in the queue.

Anyway if you think it is important for the user to control this behavior then we could add one more attribute that set the queue length.

**Comment by jln-** [comment] 2017-12-10 21:49
Well, your use case make sense but in practice, if a need something time critical plugged to a remote, I guess I'd just not set a slow rate to avoid problem you mention (and cook my filtering stuff and threshold in patch).

Maybe it's just me but the first common use coming to mind would be to set remote with a slow rate not to refresh too often gui or something so I'd definitively wont want to deal with that list of n last value everytime I need that for something that simple. Do you guys ?

As for the attribute name, I dont remember having discussed it. Still think it is a bit misleading as it is now (prefer refresh if we are to keep as ms) but I dont know how to do the change myself and we sure have more urgent to do for the moment.

**Comment by avilleret** [comment] 2017-12-11 07:59
the thing is that o.remote share the same queue behavior than o.parameter and this cue does definitely make sense for parameter. So i'll keep it. But I'll add one more attribute to control queue length. Default to 1 for remote.

Concerning the name, if you prefer `refresh` instead of `rate` as a shortcut for `refresh rate`, that's your point, but I'm in favor of consistency accross implementation and rate is 43% shorter than refresh. Just tell me one last time your choice.

**Comment by bltzr** [comment] 2017-12-11 08:24
> 
> the thing is that o.remote share the same queue behavior than o.parameter and this cue does definitely make sense for parameter. So i'll keep it. But I'll add one more attribute to control queue length. Default to 1 for remote.
> 
great, thanks !
> Concerning the name, if you prefer refresh instead of rate as a shortcut for refresh rate,
> 
I guess the point is that ```refresh``` is rather a shortcut for ```refresh interval```

As I said, I can live with ```rate``` and most of the work of changing this happens in the patcher and ref pages - so if you want to take care of this there, I can do the change in the code, @jln-

so, you have the last word, @jln- … tell us what it is

**Comment by avilleret** [comment] 2018-02-05 09:57
since https://github.com/OSSIA/libossia/issues/356 is closed 
I think we can close this one too

**Closed by avilleret** 2018-02-05 09:57 UTC
