### ISSUE TITLE
[max-ossia] [ossia.parameter] @type impulse is not working

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#513] opened 2019-07-06 15:31 UTC
Hi

opening [ossia.parameter] helpfile, and test [ossia.parameter my_impulse @type impulse]:

the pulse (bang) is not coming out again from the outlet. 

if you attach a [ossia.remote] to the parameter, nothing happens.

**Comment by evanmtp** [comment] 2019-08-19 01:45
I can confirm this. Interestingly, if you send the [ossia.remote] something other than a bang (e.g. an int), the corresponding [ossia.parameter] will output a bang.

<pre><code>
----------begin_max5_patcher----------
471.3ocuUtraBCCDEccxWQjWmhhCPZo+Ace2UUgbBiZMJ1NxOnfP7uW+HgGs
jVTJzEXjmLx24LyMNaiiPkh0fBk7XxKIQQaiih7gbAhZ2GgXj0U0DkOMTkfw
.tFkFdlFVq8w2.McwnK7QDkKuCm2ErzTVVCJ5Bv8v71nbCixqAs+rwmj5wQZ
H5p2o72lKgJcnZue5nrzDrecB1sNd1nrjWObvBit6jybA2EG6VR+ifxEMv4H
EeqHEeqIszn0BdW4GNL8lFHHOpjveCsWtiPdFZeQKILPCx4.mzBT1Owc+TV3
+KeR2ZOXhG.lb3CaU+s4oPonjQ6QHgs4IVioVA81PPo1emqgbOZXPOtcBW3o
NuWpyGB0FVIH+QV5c.WbMGvgWXKxbqSytAjNTa7jquMNP4+uKVBLgFtTKbe1
37AZiyZcyy9kg63qM1LwBnNgFX9YPo6m6ywKdX7liytLdOdL6SAUS4e8qtdY
bwOsInDFYUW02dGSxAgVXgkxIZp03eHmYgbNaa9R0o3BzI+JnyjAoSnMRZZV
ARUaxdIrtlkBoa6Co9sTdXq+EYjDVQ6xOj.QZmtZ6n0H8kEZcQ3BAjyUI4FZ
6HzBmURuijaulP0PBb3Mtw6h+DfYW0Rh
-----------end_max5_patcher-----------
</code></pre>

**Comment by vincentgoudard** [comment] 2020-02-24 23:39
@evanmtp it does not output a bang, it just outputs the value, which you happened to connect to a bang in your patch...

**Comment by evanmtp** [comment] 2020-02-25 06:15
Yep, @vincentgoudard is correct, my bad.

**Comment by avilleret** [comment] 2020-06-30 21:41
I can't reproduce that error, I added a test patcher with aa5fe8f7
I'm closing this issue since it's pretty old.
Feel free to reopen @maybites if you think it's not fixed yet.

**Closed by avilleret** 2020-06-30 21:41 UTC

**Comment by maybites** [comment] 2020-07-01 07:30
it seems to be fixed.
