### ISSUE TITLE
[ossia-max] crash when cutting ossia.device in ossia.device help patcher

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#342] opened 2018-01-02 13:53 UTC
in tab "Network exposure" select ossia.device, press cmd+x and kaboum :

https://gist.github.com/avilleret/894196082d34e1d8f8c22149c73b8bf6

**Comment by jln-** [comment] 2018-08-04 20:48
Cant reproduce. Closing issue

**Closed by jln-** 2018-08-04 20:48 UTC
Labels: bug, need testing, release critical
