### ISSUE TITLE
Issues with j2ossia.sh

### ISSUE THREAD

**Issue by evanmtp** [OSSIA/libossia#489] opened 2019-04-10 23:08 UTC
When converting some Jamoma 1.0 patches to ossia-max, I noticed a couple of issues:

- The script indiscriminately replaces "symbol" with "string", which ends up modifying objects like [fromsymbol] to [fromstring].
- The script doesn't remove @ramp/drive when converting from [j.parameter] to [ossia.parameter].

See "before and after" patches in the attached zip file as an example.

[j2ossia_bug.zip](https://github.com/OSSIA/libossia/files/3066201/j2ossia_bug.zip)

**Comment by bltzr** [comment] 2019-04-11 09:20
Hi @evanmtp !
I have just made an attempt at fixing the symbol part. Could you please try if that works ? (I haven't tested)

For the `@ramp/drive` part, this is a little more tricky (and my sed skills are very limited), so could you please try to add this at the end of the file:
```
    s/@ramp\/drive ([a-zA-Z0-9~().\/]+)/ /g
```
and see if that works ?
if that doesn't, it might worth checking sed's syntax, and or ask for some guidance to @jcelerier or @avilleret 
(the problem is that we want to just remove `@ramp/drive someMode`, knowing that `someMode` is just one symbol without a space - we could also do it the brute-force way, by doing one line for each mode, but, still, I'm not sure how we just remove this (aka replace by nothing) )

Hope this helps

**Comment by evanmtp** [comment] 2019-05-04 00:03
Hi Pascal,

Sorry for the slow reply! The `@ramp/drive` fix seems to work here, as does your symbol fix.

**Comment by bltzr** [comment] 2019-05-04 08:26
so I'm closing the issue, please reopen if problems arise again

**Closed by bltzr** 2019-05-04 08:26 UTC
Labels: bug
