### ISSUE TITLE
[ossia-max] max freezes when a view of a model is initiated with [bpatcher @name my_model @args model_idx]

### ISSUE THREAD

**Issue by ktatar** [OSSIA/libossia#380] opened 2018-03-21 00:24 UTC
Hi all,
I can reproduce the following bug. Download these ossia model and view patches: 
[ossia_xbox.zip](https://github.com/OSSIA/libossia/files/1831678/ossia_xbox.zip)
Put the folder somewhere in the max file paths.
To reproduce the bug, create [ossia_xbox.model xbox], then create [bpatcher @name ossia_xbox.view @args xbox]

**Comment by avilleret** [comment] 2018-03-23 14:25
thanks for the report, does it happen only with bpatcher ? i.e. if you load the same patcher in as an abstraction instead, does it work ?

anyway, I experienced such an issue on Pd, I'm gonna to fix it this afternoon.
Hopefully this will fix this one in the same shot :-)

**Comment by ktatar** [comment] 2018-03-30 17:38
I just tested. Yes, it also happens when I initiate the view as an abstraction.

**Comment by jln-** [comment] 2018-03-30 18:38
I quickly gave it a look and it seems something weird going on with nodes object. It seems there is a feedback loop although nodes should not output anything when using setnode message.

**Comment by avilleret** [comment] 2018-04-03 20:08
I thought this was related to https://github.com/OSSIA/libossia/issues/385 but it seems to be a little more complex

**Comment by avilleret** [comment] 2018-04-04 09:30
could anyone check if f8db61392e904255325ed2b783b121d450e853c8 fix this ? @jln- or @ktatar or even @bltzr  ?

**Comment by jln-** [comment] 2018-04-09 15:53
It does not but dont think it should. Problem is apparently related to Max's [nodes] object that causes a feedback loop and not so much caused by Ossia. In the view patcher, if I disconnect outputs of analog1-x, analog1-y, and analog2-x & analog2-y going to [nodes] input, I dont get a Max's hang. So I guess [nodes] is the culprit here.

**Comment by avilleret** [comment] 2018-04-10 20:35
ok so if it's not related to OSSIA, I mark it as`wontfix` and close the issue, thanks for the test

**Closed by avilleret** 2018-04-10 20:35 UTC
Labels: wontfix
