### ISSUE TITLE
[ossia-max] assigning address to an ossia.remote with no argument won't work

### ISSUE THREAD

**Issue by vincentgoudard** [OSSIA/libossia#545] opened 2020-02-25 14:20 UTC
If an ossia.remote has been instanciated without an address, it will not send values to the corresponding ossia.parameter, even after address has been set with a message.
See patcher below.

<pre><code>
----------begin_max5_patcher----------
873.3oc0Y0zaaBCF9bxuBjOmEgsiIgdrW1gcXRaZZGllpbBtsTA1QfoKaU8+
9.aSZZCz3DvITojTgw3G+79752OnOMdDXoXCKG3ck2u7FM5owiFoFpZfQlqG
ARoaVkPyUSCrRjlx3RvD88jrMR03+7qe6KeudTdQpnPlvjpmw2L5Zpb08w76
tIisRpwD4Sl5OwCGLu5OggpKvS889s4YhiTqtX4CeBund4uUvk4w+iUcKzro
9ufZLuFTX0XOOdb0OStjbKfPrfayuTb65e74SkYvf.KXVfqY1sIhx0nYRfZm
DXBTIOKp1JdD+peQncHgdYj+cMS+..vDOvRJ+Nv1obqHKkpVuf8YNh.1hdFM
kIYY2v3zkIrcMucl9or7b5cr8DVZTTV4s7tNg1hwA9NJLTovDsYA5O2BqSSp
OZNnIdhNexLAoTYeeWoxKNKpb2bxIgAth9gmE5yY+oDs87wSDzH0l8T8uQF+
aKLLu1nraDNefiooHOOlNMikJjLOQwp6alu3CGrSmKxtyySLeajyPvE1y1bt
1YQuwnKoisVw2h76H5G1DYzbUJWaz7F0aLXXDIal100ABNDOjCjq0RLB6J1+
QHMFFF5J5Gd4OsahuuLo3TCuimuv5zYua3cz.I7t6NsiFTg2aUyObDAijC6R
zcT+Ecus1LiDrbOtP5ky3QdRgmh7Gcmmy7w6T.CTaCpxrskVKKVZDQXCGygC
jzXvPhibrOOAxZSlqUWcrriVdq0Un1H4Gbbx6BvYroZ8mSsyi.X2Zrd1vnuZ
iR4hLxAe.JHA5tpQIej6qFC6da0yOmcUepUbYdEncuhKxvnfK2kWBOfp25TM
NFwtS0Zc3JPTOEHIl+1+wLpMV03u1.jKJxVUia8Kc06k8VDKWFyoxXAemIU0
Q+NSRjEUZWZ0paKzuYUaAZjdRcBop26p0jrabBZARUur+tyIqDNXyBme2fN7
HftalSeaLmy6Ajf13hf5CWDjMt8n9vsGZiNg5CcBYiaOrOrdDK.JrGvYlE3P
bwgKHwdjcNCgtHtuM9J8gqRUWA1xvNAjMQhmsGN5T2z0qejkkalrBhxpTdPn
ryKlntLlquTUKMHi8Xb87UEcBnYk0fHKK.oHSss.aBzs7AREkJFuH1HZkjqD
RUEP7xpaxWS07PUnz3mG+ev5+Yb2
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment] 2020-02-25 21:21
More precisely, it seems to be the case when ossia.parameter has not been set an address. 

If ossia.parameter has been instanciated with an address, ossia.remote instanciated without one can bind dynamically using the 'address' message.

**Comment by avilleret** [comment] 2020-06-22 20:46
I can't reproduce it with b48724a4.
I'll add a test patcher for that case.
Feel free to make it fails. :-)

**Comment by avilleret** [comment] 2020-06-22 21:29
I'm closing this one for now, feel free to reopen if it happen again @vincentgoudard

**Closed by avilleret** 2020-06-22 21:29 UTC
Labels: ossia-max
