### ISSUE TITLE
[ossia-Max] give access to specific addresses of a (pattern-matching) ossia.remote

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#217] opened 2017-09-13 20:14 UTC
one of the aims is to eventually be able to do (in an efficient way) what the ossia.remote_array abstraction currently does (partly described in #205)

one idea was to have a 2d inlet to ossia.remote that would be used to access to specific addresses of a pattern-matching address, such as spat.{1..32}/source.{1..8}/gain.{L,R}
in this case, e.g. sending (3 6 R) to the right inlet would allow to address spat.3/source.6/gain.R when sending values from the left inlet

following this idea, we could also have ranges of values in the right inlet, such as:
 ({3..8} {6..12..3} R) to the right inlet would allow to address spat.{3..8}/source.{6..12..3}/gain.R when sending values from the left inlet
but maybe that's a little bit over the top ?

a last idea I'm even less sure about:
sending lists of values from the left inlet (prepended by list or something) would allow speaking to several addresses at once, but:
- how do we decide in which order messages are parsed ? That could e.g. be, in the above case, spat.{1..32}/source.{1..8}/gain.{L,R}: starting from the lowest node, and enumerating, such as:
  - spat.1/source.1/gain.L
  - spat.1/source.1/gain.R
  - spat.1/source.2/gain.L
  - and so on...
- what do we do with vecs and lists ? This is where it really becomes hairy ! -> With floats, that's relatively thinkable ; with all addresses being of the same vecnf type, that's still imaginable ; with lists, it begins to be really weird ; with arbitrary types, it's just crazy !

opinions ?

**Comment by jcelerier** [comment] 2017-09-13 21:12
For now I added a simple way that allows to send message to one specific address (cf image, with the message push_one). It will simply try to match the sent address with the last part of the addresses that match with the remote or parmeter.

I'm a bit wary of anything that will have patterns in them: the problem is that whenever you have patterns in the input message, you have to create and apply a regex, and this is a very slow operation (eg for a simple regex it can already easily be 100s of milliseconds).

<img width="737" alt="capture d ecran 2017-09-13 a 23 08 42" src="https://user-images.githubusercontent.com/2772730/30400903-a6f816cc-98d8-11e7-90bc-c522324d47b3.png">

**Comment by jcelerier** [comment] 2017-09-13 21:18
to send bundles, why not use a dict ?

**Comment by bltzr** [comment] 2017-09-15 07:25
(for information this function has been renamed from 'push_one' to 'send')

> to send bundles or at least many messages, why not use a dict of address - value ?

that sounds like a good idea, we have to imagine how this would work 

another (non-exclusive) option would be to group messages between some 'tags' such as start_bundle and close_bundle, i.e. something like that:
start_bundle
send address.1 0.2
send address.3 0.4
...
send address.n 1.12
close_bundle
 
opinions ?

**Comment by jcelerier** [comment] 2017-09-15 08:19
> opinions ?

the second way (sending multiple delimited messages) is much more bug-prone and hard to implement imho.

**Comment by bltzr** [comment] 2017-09-15 09:14
okay, I'll bury it, then

**Comment by avilleret** [comment] 2017-12-05 14:55
this should be fixed with [address( method I guess, @bltzr  @jln- could you confirm ?

**Comment by bltzr** [comment] 2017-12-05 15:23
well, this is apparently not working currently: we can change the address attribute, but it does nothing at all
![addddddress](https://user-images.githubusercontent.com/113982/33614775-8e4feff0-d9d8-11e7-9cc2-eba68eac3ba6.gif)


also, this needs to be ported to Max

**Comment by avilleret** [comment] 2017-12-05 20:31
this is done for Pd with https://github.com/OSSIA/libossia/commit/079b71e41d66c078130ffb2d7855548581366d1c and ee083d6fff7b4d08ab62e130a2d667b42b875edd

**Comment by bltzr** [comment] 2017-12-06 10:55
changing the name so we just need to port it to Max now

**Comment by bltzr** [comment] 2017-12-06 10:56
so, this is done with (select theAddress) now, right ?

**Closed** 2017-12-06 20:25 UTC
Labels: need testing, release critical
