### ISSUE TITLE
crash with ossia on ubuntu-studio 20.04.2

### ISSUE THREAD

**Issue by mikmodulorg** [ossia/libossia#716] opened 2021-03-03 09:41 UTC
Pd 0.50.2 can't start with ossia v1.2.4
terminate called after throwing an instance of 'std::runtime_error'
  what():  libavahi-client.so: not found. Functionality may be reduced.
Pd: signal 6

**Comment by thibaudk** [comment] 2021-03-03 10:10
Hi, 

Could this be that libavahi is not installed ? 
could you try installing the package with
```sudo apt install libavahi-client3 ```

**Comment by mikmodulorg** [comment] 2021-03-03 11:46
Thanks!
unfortunately...
libavahi-client3 was installed (most recent version 0.7-4ubuntu7)

**Comment by thibaudk** [comment] 2021-03-03 14:20
ok, I presume you installed it from deken ?
Or did you build it from source ?

**Comment by mikmodulorg** [comment] 2021-03-03 17:18
Yes I installed ossia v1.2.4 from deken
and libavahi was already installed...

**Comment by thibaudk** [comment] 2021-03-03 17:56
Ok so the issue is with the package. Thanks for letting us know.
In the mean time, if you wish to build from source, please refer to 
https://github.com/OSSIA/libossia/wiki/Building#building-ossia-pd

**Comment by avilleret** [comment] 2021-03-25 22:27
thanks @mikmodulorg for reporting, this is indeed an issue with the package which looks for `libavahi-client.so` instead of `libavahi-client.so.3`.
In the meanwhile you can create a symlink with :

    sudo ln -s /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 /usr/lib/x86_64-linux-gnu/libavahi-client.so

**Comment by avilleret** [comment] 2021-03-25 22:55
@jcelerier, I just discovered that Servus hard-code libavahi-client.so [here](https://github.com/jcelerier/Servus/blob/1883e6cb4a8beffb92bfe929483380a115d44dd2/servus/avahi/servus.h#L151)
I'm pretty surprised while this file is only shipped with [dev package](https://packages.ubuntu.com/focal/amd64/libavahi-client-dev/filelist), do you think it would be possible to change it to `libavahi-client.so.3` ?

**Comment by jcelerier** [comment] 2021-03-25 23:01
ah wops indeed. seems that it's so.3 on both centos 7 and latest archlinux so that should be safe to change

@jcelerier note to self: also check the pulseaudio lib

**Comment by avilleret** [comment] 2021-04-03 11:37
fixed with d8699824

**Closed by avilleret** 2021-04-03 11:37 UTC
