### ISSUE TITLE
[ossia-max][ossia-pd] ghost nodes at the root

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/libossia#284] opened 2017-11-15 12:23 UTC
```
<pre><code>
----------begin_max5_patcher----------
1208.3oc6Z1sbapCDG+Z7SACW65hD9i3ycmmiLc7HCx1pEKwAIRcNY56dER.
V7g.aOz1oIbichVjP6pU+3uV7ayb71ytf4dt+i6ytNNuMywQ0TdCNE+ui2Yz
kvXDWcYdmwbN5H1at1l.eQnZGeIgwwtLd3+kgSeszNM6LKSDiEpdCJZkKdMF
q5V40kfDgmHzi6RwgB87Y6pE9ycWFj+IvGj+EDtv28KEcQOthWSv5q2yqxDI
RM3r8e8SqLlIDZ4DAl21OlMK+i42nmSweWNfsb7D2DTDua+0+t7WsmtQ4oK2
zxeMbpfNcJeywFmV3JE9hi2ARL9EbJmvnFqENdnjDilcL5Rd.3qL0.sYdUSD
ptIXUSo3WHk8OnpUTpzCER2KKU66WVuz65vvhvozLhZpnaTtTLqb.KCJqW+T
dfH..y+Z8ReUv4I+qwE4x1wXV32vQFw.Y1QBlRnIoXNlJPhhYWk4H7ATVrX2
AFUvI+uZBptGcX+.JDasyTzYs28uoDTbo+4cLkDwn4ShZw57lKucO6BTY34e
d0YTWAEkzQmkq7x3hEiboSlw2iRyWJ1qy1JWg7DLVbcSU8KFePTXNgPoMhhB
Vhciojim5ou6YRim6arUV36xnZq6ja0D63nWpGsEn33h8d0G9KHJ4LRfED8R
.zuxHlhjN5IdXJKNtl+ps7RGVhjYwg3uShDmT2HyjA4kSRJSh7pVkiHGwbQ8
1Dni75szZ2uror8E6R2IvmShkdQ8KnFW1bKoIkpV68QqZRrDDAYAzzXmbKKy
dK7K.XolYYvsMAX1fXVAYcAyp6xVgZ1.aM5dW.NKPN6ftggc1.d0fdM.eA.E
payVqbOqruaf+cKLvA4f2HKrGd3swDGfKNHabP93.Lxg4jCxJuAd4svLuGtY
OryA4m8yP6mi1OKsWdpMlZ2bU6zog4qcyXaRGZxZaYeHlactKiyInEInT41D
AN0UlQhV.+rfIXM6ScbLrg0tcZKXYXfRJIXKTuwpStrEA0yMDUODBuMFGXZS
I11.58GLjC9cExWAF+PN7uiPd9S6haqyv9YBezH8Z0SI041992QftufL3gCx
0enULgVRXb+xrtdjuWN1NZm9wW6PBQJYelP2otz67PnSoFg8n3BfX0CouEN5
Un6r1Nb0ecM2Z7UoBFaUpP8lRsvpgUoBmToNoRcRk5jJ0IUpSpTmTo9tUkJX
Rk5jJ06WkpYdjw6Ap+Ln6QspVnArH0YYmxU6OswVJikzEi3002JQ6TjxzigR
Md6Qpgd+oBcUP8Fo.ZmXrdAehLQ1H7B9.a70G8PQCVB56M7A+v7F9f9PiCjM
8F9ldCeSuguQn1IRIjibkSfA5m9.B5FeMU4j6oxIqz+7VJDgOU5joRmLU5j2
akNYOIJKF+q7H7qUhlfqTjYP.7ibUSNixCOeVjlE9aHj6qDwCVC+vV0j5JLF
+Zl.Lxo29zTMSdWVyDiiVOV0LABzaMW0SlyTIS9kVxD0J7X7S.OvnrWAaeve
B3fNqkBvvcU8xbEqz6Uyo71qGC3rrzvx6Ywuxb2qSK4BmfPqzj+b0zv3ZNQh
hvlR1kqp7bEWZ8fslbMNrS9DowgaZbnl1Glw9gXZd3E4c9Gy9I71OGXA
-----------end_max5_patcher-----------
</code></pre>
```

it seems that when some child nodes are created like this : 

    [ossia.model blah]
    [ossia.parameter foo/bar]

there is a ghost foo at the root of the tree in addition of the one behind blah, eg the tree looks like 

    /blah/foo/bar
    /foo

**Comment by avilleret** [comment] 2017-12-06 09:36
related to https://github.com/OSSIA/libossia/issues/275 ?

**Comment by bltzr** [comment] 2017-12-06 10:29
yes, that's the same one, apparently, so I'm closing #275 and adding my comment from there below: 

it was repeatedly reported that some ghost nodes appeared in score when working on a (connected) device

I just tried duplicating a [synth] abstraction (in the synth-example patcher from score/Documentation/Examples/Max) and could notice this from a connected client:

print: parameter create synth:/modulation/ratio
print: parameter create synth:/carrier/frequency
print: parameter create synth:/ramptime
print: parameter create synth:/modulation/index
print: parameter create synth:/gain
print: parameter create synth:/cutoff/frequency
print: parameter create synth:/pan
print: parameter create synth:/synth.5/pan
print: parameter create synth:/synth.5/cutoff/frequency
print: parameter create synth:/synth.5/gain
print: parameter create synth:/synth.5/modulation/index
print: parameter create synth:/synth.5/ramptime
print: parameter create synth:/synth.5/carrier/frequency
print: parameter create synth:/synth.5/modulation/ratio
so I guess that the problem is that the parameters are created, and then are moved under the model node, and probably not properly 'zombified' so they stick there and stay displayed e.g. in score

**Comment by avilleret** [comment] 2017-12-08 14:13
I think those ghost are there because when removing a [ø.param] we only delete the end node that hold the parameter.
To avoid ghost we should take care of asking if parent has some more children when deleting, if not, then ask all other objects if one still need it.

**Comment by avilleret** [comment] 2017-12-08 14:13
Pd should be affected too

**Comment by avilleret** [comment] 2017-12-08 14:34
I confirm Pd is affected too

**Closed** 2017-12-08 14:58 UTC
Labels: release critical
