### ISSUE TITLE
[ossia-max][ossia-pd] default value output does not follow priority on model initialization

### ISSUE THREAD

**Issue by jln-** [ossia/libossia#366] opened 2018-02-11 20:43 UTC
As shown below, parameters' default value get sent in alphabetical order on model loading and not according to priorities set to parameters.

<pre><code>
----------begin_max5_patcher----------
1566.3oc0ZssbihCD8Y6uBJdNICRbyddJ29KlZKWBP1QYvBWfbtrSM+6qPBH
fsAjATr2pxDWSKCmiNcqtaIk+LelYPxG3LSieZ7KiYy9y7YyDlxMLq3+OybK
5ivXTl3qYtNNgteq4MxgxXeFiE1KsrCwBegP2rJEGxjuXGuE2YciA.Bx+v0J
+2P3cVF+SwyvegI6YwXl.BXgUoI1m6vxWCGBCy.DciY0CRhDXmD75sPuRFrN
IcKR.sWImRwYXJCwHIzygW6PonsXFNcElhBjSTqu3LgVRYPts+Ned9utQQgj
hemy6RRyvevjykrLB5tT71DF13Ga+b01jnefPnyRwcsspMy.t18H41cI4h+c
RI22raAVIZLNUbDgidt5LbzcvgisxqqlvwfffAENJmYZKbzVwvwNogVTQNg1
goQFYX1PDNOGwG9vdzMPq51I0KnZ5UmneMJWN.sHW.0jqNQWKx0qIDpgsw8r
TxlM3zLiaACJJC.qksdxzMfihgYcB+WBm82SUBOaAcb880XUBv4WknWdo0pD
CPHcWXcmq1Exyu6ud40UmPJWmnYgz+7Ex930knuk8TYVwAovxBdfdKf3zaeJ
s0qBXgZIE6lJZQ4R4yF7PK85JK945NlfySqXKUTw5hAeIXPM2hbTTzfZcYgk
VaQ1RwdX5jFWyMwXuvSKMwn3dK5F9KUSL1t57jW.vg1DS675JsIF8JjKGZOL
+ORGKVlnUcbvsvbgzQMzBiMvQ2sv3pXFwNYx0WGLvENZpCFE2GbmD36qAlvv
vAIetR2sKPKMvn3YvzMKFWPWfXxiSKYxaD76uQxHAjXB6yFsVrdcdPnfX25H
7m25XWiKwIg+FGEkh1jEllDGWOqRXLI72rW3wxadotcY9mWN9AjC71wCDrg6
OajwJHIMhOApQ0S3Pg0ubDaOwxWOnSqNTqS3spZ2DuM.G0.vS6+TBzu7eV0o
ubFMqxswy+S3BBuWRNF0vdlIZ2tZlmU6Qx80ulHdQKtoxDgJMYUYJEm6xkO+
WVQobQjwmL6SkqW9XQ44Rj+Z3dgT5dRUfmHpad4KrRBfKES9k10N7UQC4kZP
tKUF5TGdyjcXJgVWXaLbDdMZeLa05DJKi7uBBJNxsSL9ZTHt0GlxqDJlcOjR
PwkyOyMojnDZNIZn04lKg6W7Ujx0k0mLhuAEs6DOLOHhqKsLXFeRtOK.kJV8
IyPAKGjkjD2bnpmKFulUL7NBkdfJxR109f78l7RGOaPBevsc8tEijsZOUN5J
dVE1pLzaMUaFJNtHWcyW+GHJg2QClQjt.nU0fGkW.zbj2NwHQ7n3P76jHlLE
S8fA9WmrqLHxrxKGQ1fyXMsw34uZZ4nJFbS6KSbthg2tKlOKZ9EZbSz0WRVO
gbC6cUc6vKTfPYFO+7y0G8XR1VoMe44SWbL0GVRo8bgGlObQCfZoBlZfcPMr
Yk0wJxpL8RnrIgp9fMhhh3aVmW11HljwLtuHCAOHh+ia9G2yU8jTdMQikKGg
t65K1RssiJBOr1Hc2YVaa9peeS+D5a24Hiue5omFiNa4O13ae00v9.6BIgO9
3iCSBkUokyJ2kCWB8TQBUCrKjD9vCOLBIzFZMVIzUYIrWvt3YY46BqQV1oIk
piu7bccrzZJUGkSGzOgt3dhfffBOw53DTiBdt07K.KvXh98jkVfK0piwV8UH
8RnKtiAgPs5XFgqn3XXJNIAs4JfJ6J5mPWHWQ99ZiMjGazfDbnbBBrJ9qEDp
fhC5TwaSsAJn1Jyltk6u1eaLg11FaDhQ93m1OjkrOMrbRUzjpQSdv2nFiPq1
s+up1nQ92SonfykCNJxAeMxAaE4fmF4.TQN31JGJLJsTbJjhWXyPF4gRdH8J
NZxtCQZgR42loAPB+Qm9op.4qJPViDHWIY6DnkSDN8Mg7mHbf8IbvI.HGElP
tS.NPUBEfdSARdpfzT3jfpDM.mhvansJHMI9IKUVxNEKk.JkEZwTfzBUPxep
Ppu7P.uoBodyPLEQD.kRh6LEH4oJRistDvUUjfiEIURvBmhL4.kxQ.lBjfpV
VezpmB.cbjmr+nCt.ubHN3h6N3R6N9B6Z+x5N7h53H+24+G.N5DU+
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment] 2018-02-11 21:13
this have never been implemented but it should

**Comment by avilleret** [comment] 2018-02-12 22:37
to do that we need to wait that the patcher is fully loaded and all object registered then fire a reset message to all root nodes

the question is : how to get notified when the patcher is fully loaded ?
maybe this is the aim of the loadbang method....

**Comment by avilleret** [comment] 2018-03-04 23:21
I think we can close this one, isn't @jln- ?

**Comment by jln-** [comment] 2018-03-16 16:26
I think so. I assign this to myself and'll close it once I get a test patch made and setup.

**Comment by jln-** [comment] 2018-03-19 11:02
Working on a test patcher for this, I got surprised by how it actually works. So just checking whether my expectations (based on how it works in Jamoma IIRC) are wrong or if there's a problem before finishing test patcher. (I think my expectations are, but just checking in case)

I have the following namespace:

`
model /test_priorities
param /test_priorities/first @priority 3
param /test_priorities/second @priority 2
param /test_priorities/third @priority 1
model /test_priorities/subby.first @priority 10
param /test_priorities/subby.first/zzz @ priority 100
param /test_priorities/subby.first/yyy @priority 99
param /test_priorities/subby.first/xxx
model /test_priorities/another.last/
param /test_priorities/another.last/zzz2 @priority 10
param /test_priorities/another.last/yyy2 @priority 5
param /test_priorities/another.last/xxx2
`

Init order is as follow:
- zzz
- yyy
- xxx
- first
- second
- third
- zzz2
- yyy2
- xxx2

For some reasons, I thought priorities were handled level by level. That is: first, second, third, (THEN checking priorities against sub models), zzz, yyy, xxx, zzz2, yyy2, xxx2.

@bltzr @avilleret @matcham : Is it the expected behavior ?

---
test patcher:

<pre><code>
----------begin_max5_patcher----------
1896.3oc6aszqZiCEdM2eEQr9NWk37dV0pN2ccwnYZkFopQn.w.tMjDkXtEn
p+2G+HAbH1AWHDPiXQ4VNNIeG+cd3SNX+imFMdZ1FX4Xie23KFiF8imFMhIh
JXT02GMdUzlYIQkrKabJ76YS+53m4CggavLw4EnTrw6+vm976+X8fnX1PjK+
2.l0ByKfkvTbDFkkNo.NCyA2x4EymMbC.z+v+DP9z3eqtsz0qPoIPLSIrNHL
aMtVpYkzR71DHC48XFgmsDktPG7n2wOe5I5GO2GTxq+ye95G9zq+gDRwx8Dj
RnISIc8n+wxz7pyJpA7LnkYYqVQlTs3kW2jS.DFajUDCKjwKdmfWr4VOmf.l
d5x0SyqHwzAh8mCytjWHbVdTATFoDpWDD21442suBPJk.NiHHk3wet3s4P90
SdVj+0m7E1XpARFUEbBpxiEu63xTZGyWb+0Cq9knpSgWKpZZT5BJcQRfbdL1
JXYYzBXKJaNpnDaTBmkkFafWhJhM1samw1saM1rYC8+CneAP+FPF05qG0xiS
.Ntmian0YvspArseXOGytBuTFS4nES4B3IVrt5wqmBuqe75rr0oX4Y7s0ysB
vrxdmfrbkRVNmgWkR7ZQVzH0mq3rKIvUYptDioxHNfVqJXyCO77t5o5NEdR8
xXo65W5hkaSBgo2pn1lLStc34Twk0YvWJwqEewmX8KYwWOPBa4oEaYEvzdWm
AhsTiWK1pZl0uzEaQTIrkqVrUHqJ.6ghrTBWKthOsNKpZJC9Co1eCA+9anRz
TTBBuUTyylOuDVofrhnEqZOIa12fwwEQKJmUjkjHVl9rDzrugWVjsdwRQ4vz
noIvksuA9.u0dfoKVkECaHg+lHBpoXJVq5YEb0TXr3UovN6aay3b.m44g1lt
pL0lcZpkXXO8yukskTN238iVar31yJC5Hh8mPWvhRxjQPAFMNJOWP7Hgag5E
70L1CJ348hPobQl6EU.oNC76+fznBxDCSlUqK39xaBpy2PeLDaTQ5ZDSU3BI
9iOU+.q4h.96e.LYE944XxqFTvqhZv4NVhvONKGlhREsfMFNFNOZcBdx7rTb
IZGSAsnDtjwmGMCp7lSiVwmcuu.EkTO+Fun.EmkRUhFbMUbMbjHXW9aaJNYX
WQZTtjal3sR3EECVRljqKmFUvhK4YO.0ChyxRZNz96KANGWMbNJM8HVDmkqd
vBzhkcbuSyHCtpqmMajxIqS4iNgjuAOoL5slrMNJIoJWcyG+lnTzpHLDi3l.
f49Aak0vp4HuIYjXhW7L32QwXdBHQmAxkixqchFu2JGiV.KwMkgIY2ZJoU1b
hn00oTmfgqxSHyhlWPi91IFRJlptg7tVc63U3noKDFQHaXfnbUqyU02Hd9I6
iW4Q4hcpyBpflTsvmF3qHCY8EvV+qJmy0ffIuisBB1WaB1xI7lRvcieKBlNk
GNBd2tcJHXOsIXeuaJ+1I7snW5DtWoWNBJHQW8SC3FvqOo9yygEMufz.chec
OpO9wgRigaDJ83Z6vlUVhhdIOpfTs.FVvZF26nVWC5ugv6pJnvHTg4vQ+jFg
7eqCavk3UCtfrFcq.c0Epg2LP6KpDyPfw6xKPYEj2swHTkMwVeaBnx4z7VYS
5VAturIz9UKwl3KXSrLMUXT.ZaTbpZLi+MxlzM92ClD5ankXPpTc51W3+tBh
V.EF.KsM.7eosvfazpucBupeSgin9Cu0VBJUU45LMfNtbaRY15hY0vTUAtQS
sg75GXT592g8K6Wh1vTSOheUcv+NPG7tCzAGM0gfqnNXqoN3eE0Afl5fmRcn
RHWxitO150A0t4i1gVBMGrtr29q4im94K6UqA++r6i.d208Cdz7wGMe7QyG6
slOBtftOxqXyxtZu1LzUOpA7pRPNfMeDbAcejWYryMkf6FdY8dDLrMeDbAce
juZR3sje6DcY8dDbm07QdXnu4Mp2iZ.+cbqGAxZvhE3BZ9HOnMvSwlz6p2SE
cv+tq0ixMCVBsYw8B58HmRrpbN8tQljtw+tqyixMIl5z4Kft1DG9qVYYeaLI
cC+8SiGiRyvjRTegVW9EzrQ1blsZmkcvsYw1NQ+QqFezpwGsZ7doUicdTu9q
W+6O+wOIaWZq2oeyC3Onm9MI30eTxwKdxOrIRV8zVbwSIjmiVbGfui8Agm0V
19L1h6c.30+jTbL4Vcfdjvt.A1U1A5wVuc3sCeSTX4LPraG.N7ra0OtojB+D
HWaYm5U8B64K7GNTbqZ7FJpkW.Glj2dRE+gHkrHIuodGVC.2iwenNrFJwqmN
pYpN7dTRP14NHPuLjryLg4U+.40MZmfhXWWyRX4L1wkITwasJOHTr7.EkFXA
NTaPKSit.EnCP8.N9C0Dxan.xcn.xQCfB6Abr0.Gud.GfF331C3XoUPjYefj
VQQ98ERVmBIG9EcYHoUDqSeLmzwAmYLOLwOrWCF.naFouGZyKCZcB2rB5C9U
m.Nf4UYRBz0zZ16lVfNQJ18A+ZcdqDvKR3nMFBEji1PHGsYPZuQPTuIPNdCf
PP9mO8e.vaSKz
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment] 2018-03-19 14:10
IMO this is behaving correctly

I modified the test patcher with the behavior I was actually expecting, and it is met

can we close the issue, @jln ?


<pre><code>
----------begin_max5_patcher----------
1888.3oc6as0iahCE94L+JP44YGgM22mZU24s9vpcakVoppHRvSF2R.D3LMY
p5+80XCIPvjXCNIsU4glQ0Neb746bwGNw962MY57zMnhoF+owmLlL462MYBa
nxAlT8+mLcU3lEwgEru1zDz2Rm+ko2ymhf1PXCmkiSHFu8ce3iu880SlrdEN
IFQX.A6GLcModTypQwQrmB8I+GPyZ7EjswH130ijkiJPIjPBNMYVNZAguxA1
OXdugiOr7O7OgzOM9bMrPxhmwIKkARIheb2ckebuNnjG+u+9w28gG+qwQJ.G
kIk.SlF53V9GfooLrR+XF.srHc0J55pCu73lLp.QQFo4Qn7QxKtJyKVbSusu
OSIc3Jo4wIli.ReNLuF+.kyxByQBIEnPRAJfTB5mT3HIayPbEiNA8e6U8iFf
w8Kb8TH.qKD8wWDi4FXE7eDQU9JPUyCSVVRWzv5SxXtrTJ1NLE217AmSyX8B
Y.L1JTQQ3RTWWrWe0X61sFa1rw3IbdAwn.sHMIxf7LNOxfNMrbdX4W.pfWHP
.05ohWnj7IO9CZ6HiKX+XzZL6JxyiLd0V2wqbM2AxSZAjmrD.Qeb0hz0Ijdx
36HjrrEPVVJPVkQp2WwYcBb60gAxbXbAmmbVwFyGYNKnhtKr7Vxkh2hGr35J
SBqdgnS5hkXRABSPlHU1NjKNIIKSlKhUf76GJ.hNIKdx7wwVtJvVUxSN5B3y
zcGa4oKAPzIcw1AbbrkiBrEWbxQVArp.rTfq5hX.T0b1ieeN5Wvnu8Bt.OGG
iIaaxAoO8TApZAvpFtYEzwoK9JJJJObYwh7z33lUuuHFu3qjmySWu74liiRB
mGidtK.9Duzch4KWkFgZMB+UJZa.2aU28DWMGEojYF.50pRqT5j1TOKKlwAx
MQ7b.lNG2rJIHt9NYmAcB0OiRWn7B5Zng5LYZXVVigmz.RoWvWRYOHu62MDN
gOj0tgxQkNCb7N6FMLmtzIz085bdDvF+5jHkOFpMJOYMlsT3CR8Guq9AVqs9
72T.ZxJSy01jW6VCupRCN2wpgsjZPxPI3jlDeqoiPOEtNlL6ozDRA9U1BDTR
oBl+ovEndAmDthqcuMGGFWqeSWliiRSJWDs35xgqEGMB0g+ZiMUF12HILS.X
pGGkW5YxBpRttXdXNKtjmyAVOIIMMt8T6vEidhTMcFNI4.Vjjl0+j43kOeDr
ySoSt5XOa1LEyVmvmcFMeCYVQ3KsYaRXbbUt51O9MgI3UgDDAyMAPycS1IqA
n8LuHXlHpW7Bz2vQDdBnlNCzuNNq1IZ5NqbDdIpfzdLBM6V6Q5rG.cn00oTm
QPqxhoZQ6uPqFv0LjrYp5Vierc2NbGtxjSMlQzdb8m.7vjf9MeTc00Slc7n6
5U0qIdxNqC21q2s95CVMJ19eU4bNGDL8kk0GA6M.BtbAHOACrCFBAK.1khfe
80W0GA6N.BtbAHOA64ND9sKJMRubMZ.jnoXRz4zj3wCxc74kxT+ojA4GEVcy
lObkfShPaZT5w41gMsn.G9PVXNsZABJm0ns2T5MYT9iA7lpBJLBFf4.J1bXO
.e5VMQRhrFA7efDKnhoMDf65XFJ64o.yfuwaxxwo4z2swHPi1DqKfMAVEHXp
nMQ.tqiMorWzBrIdMrI.SS8YTfmeihcUSd7TylH.1kzjT9FZwFzJUmu8A9OJ
PSKf918ELDCf7jO+mlKvWMtuKJAT+92ZKFmzW45LQTNuXaRQ557E0pUU4zFs
WjzW+ffS18NreZ29sFx5Qn5Zv6mf0f6OAqAaIWC9mw0fkjqAuy3Z.J4Zvs20
P0f7Qt08Qsz8Qui07Q3I69nU.nQiDqKf9DceTRP+lz8QHu64d92Z93slOdq4
iZq4ivqd2GgRUAIu7OfU0QuQxJH6C0Er4ivqd2GUffA1CgfEf5B17Q3Uu6iJ
PvtACfe6B52xlOxCV8LUq2iRf5m3VOBE0fE.7WjlOxi98c64H+c7jFBfc0Z8
nXy.nQaVb9Eo2ibtETEH3plIQ.rqVmGEaRLGamutFsdzmenEYbKvRISh.TW9
FOFljRnkn9PYc4+BzrQFww1xDX4qDa2EzsVMdqUi2Z030nUiG8Na8OO9ue78
eXj2LogdM1bgdpdM1D.QeTxgadxuoHB18zp4lmi6Htaedt.SP9A7GFnvI1VD
lyG4VcabDvtvFrKbbrq04gcA17CnAPkC3s.LmO1s5G2TPgeMHWqwQtvyC45x
qZHPAtU.DcSs7B3Hz71yp3OLsjkQcf5A57ViUcoKfbWMEt2hBfnwagW4hkLt
aWmu9oI9E.yTgTiGBnAEwP2tDVNicXYBU7VmxCBZVdPOkF.f6qMnioQVA4Ki
fzfb7tTJj6kRPNWJAYKgfBzfbrjPNtZPNPIjiiFjCPpfHScHIohh7zkj.mRR
17uz3jjTQr15PmjwAmYL2q36OqAW.Q2NRemnMGmnkIbC3qC9Ul.Nn4YQIgxZ
ZM0toEJSjhkN3Wvv1IfWjvAGLjRgbvAB4fCCR2CBR+GBjCO.HTI+i69e.Gbx
o+A
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment] 2018-03-19 22:16
yes this is the expected behavior, and you're right, priorities are checked level by level : subby.first (10), first (3), second (2) then third (1). But each level enumerates its children recursively, that's why you've got `zzz`, `yyy` and `xxx` before `first` itself.

For me this makes sense because if you have several instance of the same model, then you can control the init order by just changing the model's priority.

What did you expect ? @jln-

**Comment by jln-** [comment] 2018-03-19 23:21
Yes, this makes perfect sense and it's fine as is. Not sure why I got my mind confused, but just wanted to make sure before committing maxtest patcher. 

Will do tomorrow and close the issue when done.

**Comment by avilleret** [comment] 2019-06-20 21:11
the test doesn't pass anymore, so I reopen the issue... :-(

**Comment by avilleret** [comment] 2019-06-24 20:17
fixed in max

**Comment by avilleret** [comment] 2020-08-09 13:57
this seems to be fixed since a while

**Closed by avilleret** 2020-08-09 13:57 UTC
Labels: ossia-max, ossia-pd
